inveniosoftware/invenio-oaiserver

invenio_oaiserver/query.py

* Fixes typo in `page_` variable name. (closes #25)

query: fix undefined variable name

---

invenio_oaiserver/fetchers.py
invenio_oaiserver/minters.py
invenio_oaiserver/receivers.py

global: migration of _oaiid to _oai.id

---

invenio_oaiserver/provider.py

* Fixes provider name to be less than 8 characters.

provider: name length issue fix

---

invenio_oaiserver/models.py

* Increases the size of model fields spec and name to 255 characters.
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

global: DB model spec and name length fix

---

invenio_oaiserver/response.py
tests/test_verbs.py

* Fixes missing <record> envelope in GetRecord response. (closes #67)

response: GetRecord envelope fix

---

RELEASE-NOTES.rst
invenio_oaiserver/config.py
setup.py
tests/test_verbs.py

* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

global: inveniosoftware.org

---

invenio_oaiserver/verbs.py
tests/test_verbs.py

* Fixes typo in dumping 'from' argument.  (closes #87)

views: fix of type in from argument

---

invenio_oaiserver/resumption_token.py
invenio_oaiserver/verbs.py
tests/test_verbs.py

* Adds missing field `metadataPrefix` in `ListRecords` schema with
resumption token.  (closes #88)

verbs: fix ListRecords with resumptionToken 

---

.editorconfig
invenio_oaiserver/__init__.py
invenio_oaiserver/config.py
invenio_oaiserver/ext.py
invenio_oaiserver/minters.py
invenio_oaiserver/receivers.py
run-tests.sh
setup.py
tests/conftest.py
tests/data/__init__.py
tests/test_percolator.py

* Sets are no longer created for records without OAIID, and
'updated' timestamp is refreshed only when sets change.
* UI blueprint is now registered in entry point.
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

global: record signals and entry points setup

---

docs/api.rst
invenio_oaiserver/response.py
setup.py
tests/conftest.py
tests/test_verbs.py

UUID was being serialized into the record identifier on the final XML instead of the pid_value, see: https://zenodo.org/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:zenodo.org:167082

serialization: GetRecord method identifier fix

---

invenio_oaiserver/minters.py
invenio_oaiserver/models.py
invenio_oaiserver/query.py
invenio_oaiserver/receivers.py
invenio_oaiserver/schemas/oaiserver/internal-v1.1.0.json
tests/conftest.py
tests/test_percolator.py
tests/test_verbs.py

* Removes the separate timestamp that stored the update time in the
_oai.updated field. It's not needed, because each time we touch the
record, the value of record.updated is changed, so we can use it
when creating the OAI set (closes #119).
* Adds a new JSON schema with 'updated' property removed.

global: oai.updated timestamp removal

---

INSTALL.rst
docs/requirements.txt

* Adds installation guide.
* All `doctests` including `invenio-db` were not rendered because this
package was missing from requirements (closes #127).

docs: fix doctest rendering

---

.travis.yml
invenio_oaiserver/config.py
invenio_oaiserver/query.py
setup.py

- default for `OAISERVER_QUERY_PARSER_FIELDS`
- pinned celery less than 4.3

global: pin celery and fix default config

---

.travis.yml
CHANGES.rst
invenio_oaiserver/percolator.py
invenio_oaiserver/query.py
invenio_oaiserver/version.py
requirements-devel.txt
setup.py

* drop support for python 2.7
* update travis.yml
* closes #181

global: manage flask dependency centrally

---

invenio_oaiserver/verbs.py

This PR removes the RemovedInMarshmallow4Warning warning by updating the code to the new interface of marshmallow.Field.
It was necessary to wrap parameters (load_from, data_key, dump_to) into a dictionary to give to the parameter metadata.

Remove deprecation warnings from marshmallow

---

.github/workflows/tests.yml
invenio_oaiserver/percolator.py
setup.cfg
tests/data/os-v2/__init__.py
tests/data/os-v2/records/record-v1.0.0.json

Add support for OpenSearch 2.x by dropping references to `doc_type`s
Drops the `schema_to_index` use from `invenio-indexer` (relevant for this PR: https://github.com/inveniosoftware/invenio-indexer/pull/142)
Requires:
* https://github.com/inveniosoftware/invenio-search/pull/222
* https://github.com/inveniosoftware/invenio-indexer/pull/142
* https://github.com/inveniosoftware/dojson/pull/207 (for Python 3.10)

OpenSearch 2.x

---

CHANGES.rst
invenio_oaiserver/__init__.py
invenio_oaiserver/percolator.py

- **percolator: allow lazy strings from config for deletions**
- **📦 release: v2.2.3**

Fix percolator deletion for lazy strings and release v2.2.3

---

invenio_oaiserver/percolator.py
tests/conftest.py

* Instead of relying on the default `RecordIndexer` class to determine
the percolator index, we reuse the `OAISERVER_RECORD_INDEX` config variable.

percolator: use `OAISERVER_RECORD_INDEX` to determine percolator index

---

invenio_oaiserver/percolator.py
tests/conftest.py

- **percolator: use `OAISERVER_RECORD_INDEX` to determine percolator index**
* Instead of relying on the default `RecordIndexer` class to determine
the percolator index, we reuse the `OAISERVER_RECORD_INDEX` config variable.
- **tests: fix default index config**

Fix percolator index sets

---

invenio_oaiserver/percolator.py
invenio_oaiserver/search/__init__.py
invenio_oaiserver/search/component_templates/__init__.py
invenio_oaiserver/search/component_templates/os-v2/__init__.py
invenio_oaiserver/search/component_templates/os-v2/oairecord-v1.0.0.json
invenio_oaiserver/utils.py
setup.cfg
tests/test_app.py

invenio-search offers the possibility of using component_templates to define an object, instead of defining the full mappings.
This is currently used in opendata (see [example](https://github.com/cernopendata/cernopendata-portal/tree/main/cernopendata/modules/search/component_templates/os-v2)) . Then, a particular index can pick and choose the components that it needs  (see [opendata example](https://github.com/cernopendata/cernopendata-portal/blob/main/cernopendata/modules/search/index_templates/os-v2/records/docs-v1.0.0.json)).    
This PR introduces a component template that oai-records can use. If they go this way, there is no longer the need for the index called `<record>-percolator`, since it will be stored in the same index as the data.

component_templates: allow the usage of component_templates instead of mappings for the definition of the records.

---

invenio_oaiserver/response.py
invenio_oaiserver/verbs.py
tests/test_verbs.py

see https://github.com/inveniosoftware/invenio-oaiserver/issues/243
> Please describe briefly your pull request.
- fixes serialization of from parameter in marshmallow. Before the attribute in the response was returned as "from_"
- usage of `load_from` and `dump_to`has been replaced by `data_key` in [marshmallow 3.0.0.b8](https://marshmallow.readthedocs.io/en/stable/changelog.html#b8-2018-03-24) 
- additional usage of parameter `attribute` for the special case for variable `from` See [marshmallow docs](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#Field) , Chapter Field.attribute and it's ` Note: This should only be used for very specific use cases such as outputting multiple fields for a single attribute, or using keys/attributes that are invalid variable names, …

fix: serialization of from parameter

---

invenio_oaiserver/config.py
tests/helpers.py

* UserWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html. The
pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.

fix: pkg_resources DeprecationWarning

---

invenio_oaiserver/query.py
invenio_oaiserver/verbs.py
tests/test_verbs.py

- Closes https://github.com/inveniosoftware/invenio-oaiserver/issues/264
- **global: fix usage of `from` argument**
* Parsing the `from` parameter in marshmallow was fixed in
ec51ae6, but the downstream uses of the parsed key were not adapted to
the change.
- **verbs: fix name conflict with base class `validate` method**
* `marshmallow.Schema` also has a `validate` method, receiving the same
arguments.

Fix `from` argument
