inveniosoftware/invenio-oaiserver

examples/app.py, tests/test_verbs.py
=> tests: list sets with resumption token

examples/app.py, invenio_oaiserver/query.py, invenio_oaiserver/response.py
=> global: resumption token for records

invenio_oaiserver/models.py, invenio_oaiserver/receivers.py, invenio_oaiserver/response.py, tests/test_percolator.py
=> global: include setSpec in header

invenio_oaiserver/query.py, invenio_oaiserver/response.py, invenio_oaiserver/verbs.py
=> global: initial implementation of "set" filter

examples/app.py, invenio_oaiserver/config.py, invenio_oaiserver/ext.py, invenio_oaiserver/query.py, invenio_oaiserver/receivers.py, invenio_oaiserver/response.py, tests/test_percolator.py, tests/test_verbs.py
=> receivers: save _oai informations inside record

.travis.yml, invenio_oaiserver/query.py, invenio_oaiserver/receivers.py, invenio_oaiserver/response.py, tests/conftest.py, tests/test_verbs.py
=> tests: coverage for identify and from_/until

invenio_oaiserver/query.py
* Refactors record pagination.  (closes #27)
--
cc @hachreak
=> query: refactoring of pagination

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/version.py
=> release: v1.0.0a1

invenio_oaiserver/version.py
=> version: post-release bump

invenio_oaiserver/config.py, invenio_oaiserver/response.py, invenio_oaiserver/version.py
* Adds `OAISERVER_GRANULARITY` configuration option.  (closes #30)
=> response: configurable granularity

.editorconfig, setup.py, tests/conftest.py, tests/helpers.py
* Adds utilities to load records. (addresses #23)
=> tests: record fixtures addition

setup.py
=> installation: OAI ID minter and fetcher

AUTHORS.rst, invenio_oaiserver/config.py, invenio_oaiserver/query.py, invenio_oaiserver/response.py, invenio_oaiserver/resumption_token.py, invenio_oaiserver/utils.py, invenio_oaiserver/verbs.py, invenio_oaiserver/views/server.py, tests/conftest.py, tests/helpers.py, tests/test_verbs.py
* Adds tests for record listing with multiple serializers.
=> tests: record listing with multiple serializers

examples/app.py, examples/requirements.txt, tests/test_admin.py
* Adds an admin interface to example application.
* Adds tests for admin interface.
Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Wojciech Ziółek <wojciech.ziolek@cern.ch>
--
closes #38
=> examples: addition of admin interface

examples/app.py, invenio_oaiserver/config.py, invenio_oaiserver/response.py, invenio_oaiserver/static/xsl/MARC21slim2OAIDC.xsl, invenio_oaiserver/utils.py, setup.py, tests/conftest.py, tests/test_verbs.py
=> WIP response: record listing with multiple serializers

invenio_oaiserver/config.py
=> docs: note on MARCXML/MARC21 prefix

invenio_oaiserver/minters.py, tests/test_verbs.py
=> minters: legacy PID value preservation

invenio_oaiserver/__init__.py, invenio_oaiserver/query.py, pytest.ini
=> docs: required field _oai.id in records

invenio_oaiserver/models.py, tests/test_percolator.py
* NOTE The cache instance **must** be shared with all nodes.
=> ext: cache invalidation on model change

invenio_oaiserver/models.py, invenio_oaiserver/receivers.py, tests/test_percolator.py
=> receivers: support for manual OAI sets

.travis.yml, invenio_oaiserver/__init__.py, invenio_oaiserver/config.py, invenio_oaiserver/errors.py, invenio_oaiserver/ext.py, invenio_oaiserver/models.py, invenio_oaiserver/query.py, invenio_oaiserver/receivers.py, invenio_oaiserver/response.py, invenio_oaiserver/tasks.py, tests/conftest.py, tests/test_percolator.py, tests/test_verbs.py
=> receivers: update record after set change

invenio_oaiserver/resumption_token.py, invenio_oaiserver/verbs.py
* Adds missing name for from attribute.  (closes #59)
=> global: from attribute name fix

invenio_oaiserver/models.py, invenio_oaiserver/response.py, invenio_oaiserver/utils.py, tests/test_percolator.py
* Adds API method to OAISet for adding records.
=> global: addition of OAISet record adding

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/version.py
=> release: v1.0.0a3

invenio_oaiserver/models.py, tests/test_percolator.py
* Adds API method for removing a record from a set.
=> models: remove record

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/version.py
=> release: v1.0.0a5

invenio_oaiserver/response.py
This change is needed by B2SHARE.
=> Response: fully qualify static resource

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/version.py
--
closes #74 
cc @emanueldima
=> release: v1.0.0a6

invenio_oaiserver/schemas/__init__.py, invenio_oaiserver/schemas/oaiserver/internal-v1.0.0.json, setup.py, tests/conftest.py, tests/test_percolator.py
* Adds JSON schema for validation of an internal `_oai` field.
(closes #56)
=> global: addition of JSON schema

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/version.py
=> release: v1.0.0a7

.gitignore, .travis.yml, MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, tests/test_examples_app.py
* Adds test_example_app.py. (closes #85)
=> tests: addition of test_example_app.py

invenio_oaiserver/models.py, tests/test_percolator.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> api: addition of has_record method for OAISet

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/models.py, invenio_oaiserver/version.py, tests/test_percolator.py
=> release: v1.0.0a8

.travis.yml, examples/app-teardown.sh, invenio_oaiserver/alembic/759d47cbdba7_create_oaiserver_branch.py, invenio_oaiserver/alembic/e655021de0de_create_oiaserver_tables.py, setup.py, tests/conftest.py, tests/test_invenio_oaiserver.py
=> global: initial alembic recipes

.travis.yml, CHANGES.rst, RELEASE-NOTES.rst, examples/app-teardown.sh, invenio_oaiserver/alembic/759d47cbdba7_create_oaiserver_branch.py, invenio_oaiserver/alembic/e655021de0de_create_oiaserver_tables.py, invenio_oaiserver/version.py, setup.py, tests/conftest.py, tests/test_invenio_oaiserver.py
=> release: v1.0.0a9

invenio_oaiserver/tasks.py
=> WIP tasks: fix task for python3

invenio_oaiserver/config.py, invenio_oaiserver/ext.py, invenio_oaiserver/percolator.py, invenio_oaiserver/query.py, invenio_oaiserver/receivers.py, invenio_oaiserver/tasks.py, invenio_oaiserver/utils.py, setup.py, tests/conftest.py, tests/data/records/record-v1.0.0.json, tests/helpers.py, tests/test_percolator.py, tests/test_verbs.py
=> global: invenio-query-parser dependency removal

invenio_oaiserver/verbs.py, tests/test_verbs.py
* Adds a permissive DateTime deserializer which accepts a datetime string
that doesn't contain the time (closes #118).
=> verbs: add permissive DateTime deserializer

CHANGES.rst, RELEASE-NOTES.rst, invenio_oaiserver/version.py, setup.py
=> release v1.0.0a13

.editorconfig, .gitignore, .travis.yml, CONTRIBUTING.rst, README.rst, RELEASE-NOTES.rst, docs/conf.py, docs/configuration.rst, docs/examplesapp.rst, docs/index.rst, docs/usage.rst, examples/app.py, invenio_oaiserver/__init__.py, invenio_oaiserver/translations/cs/LC_MESSAGES/messages.po, invenio_oaiserver/translations/da/LC_MESSAGES/messages.po, invenio_oaiserver/translations/de/LC_MESSAGES/messages.po, invenio_oaiserver/translations/es/LC_MESSAGES/messages.po, invenio_oaiserver/translations/fr/LC_MESSAGES/messages.po, invenio_oaiserver/translations/it/LC_MESSAGES/messages.po, invenio_oaiserver/translations/messages.pot, pytest.ini, run-tests.sh, setup.cfg, setup.py, tests/conftest.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> global: release checklist

AUTHORS.rst, README.rst, invenio_oaiserver/__init__.py, invenio_oaiserver/config.py, invenio_oaiserver/resumption_token.py, invenio_oaiserver/verbs.py
* Fix couple of typos
* Add note about Elasticsearch and message queue requirements
for usage example.
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
=> docs: usage documentation review

invenio_oaiserver/config.py, invenio_oaiserver/utils.py, tests/test_verbs.py
* ADD utility functions to generate eprints, oai-identifier
and friends description elements
closes https://github.com/inveniosoftware/invenio-oaiserver/issues/32
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
=> utils: addition of description elements

.travis.yml, setup.py
* Removes invenio-query-parser as a dependence. (addresses #139)
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
=> installation: remove invenio-query-parser

CHANGES.rst, invenio_oaiserver/response.py, invenio_oaiserver/version.py, setup.py, tests/data/records/record-v1.0.0.json, tests/data/v5/records/record-v1.0.0.json, tests/data/v6/records/record-v1.0.0.json, tests/test_verbs.py
* Search now uses elastic search instead of
the database due to performance issues (closes #156).
=> Fix earliest date check and release v1.0.2

CHANGES.rst, invenio_oaiserver/version.py, setup.py
=> release: v1.0.3

docs/conf.py
=> docs: Change intersphinx_mapping link for flask

.tx/config, babel.ini, invenio_oaiserver/translations/messages.pot
* remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm#1664
=> babel: remove extensions

invenio_oaiserver/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
=> i18n: adds german translations

invenio_oaiserver/alembic/5d25c1981985_add_system_created_field.py, invenio_oaiserver/models.py, tests/test_admin.py, tests/test_percolator.py, tests/test_verbs.py
* add alembic recipe for the new field
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1037
=> model: add system_created field

invenio_oaiserver/verbs.py
* Fixes `from` in `ListIdentifiers`.
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You …
=> verbs: fix from

.github/workflows/pypi-publish.yml, .github/workflows/tests.yml, CHANGES.rst, docs/conf.py, invenio_oaiserver/__init__.py, setup.cfg, tests/conftest.py
- setup: bump major dependencies
- setup: change to reusable workflows
- release: v3.0.0
=> bump major

.github/workflows/tests.yml, CHANGES.rst, invenio_oaiserver/__init__.py, invenio_oaiserver/admin.py, invenio_oaiserver/models.py, invenio_oaiserver/percolator.py, invenio_oaiserver/utils.py, invenio_oaiserver/verbs.py, setup.cfg
:heart: Thank you for your contribution!
> Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …
=> I18n: Mark Missing Translations Backport
